name: The Sacred Record
favicon: null
layout_spectrum: 0.58602
typography_spectrum: 0.36213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#92c2f3'
    - '#303030'
    - '#676767'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.6483602288644761
purpose: []
