name: The Sacred Record
favicon: null
layout_spectrum: 0.27252
typography_spectrum: 0.36213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.5
  rhythmicContrast: 0.6483602288644761
purpose: []
